version: '3.1'

services:

  db:
    ports:
      - "5432:5432"
    volumes:
      - ./data/prod/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/prod/minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SITE_REGION: ${MINIO_SITE_REGION}

  #worker:

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/redwood_prod?connection_limit=1
      S3_URL: http://minio:9000
      SESSION_SECRET: ${SESSION_SECRET}
      SIGNUP_SECRET: ${SIGNUP_SECRET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_PHOTOS: ${S3_BUCKET_PHOTOS}
      S3_BUCKET_MINIATURES: ${S3_BUCKET_MINIATURES}
      FAKTORY_URL: http://faktory:7419

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        PHOTOS_URL: ${PHOTOS_URL}
        MINIATURES_URL: ${MINIATURES_URL}
        GMAPS_API_KEY: ${GMAPS_API_KEY}
    depends_on:
      - api
      - minio
    ports:
      - "8100:8100"

  faktory:
    volumes:
      - ./data/prod/faktory:/var/lib/faktory
    environment:
      - production
      - FAKTORY_PASSWORD=${FAKTORY_PASSWORD}
    ports:
      - "7419:7419"
      - "7420:7420"

  worker:
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/redwood_prod?connection_limit=1
      S3_URL: http://minio:9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_PHOTOS: ${S3_BUCKET_PHOTOS}
      S3_BUCKET_MINIATURES: ${S3_BUCKET_MINIATURES}
      FAKTORY_URL: http://faktory:7419
