version: '3.1'

services:

  db:
    ports:
      - "5432:5432"
    volumes:
      - ${DATA_FOLDER_DB:-./data/dev/postgres}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${DATA_FOLDER_MINIO:-./data/dev/minio}:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
      MINIO_SITE_REGION: ${MINIO_SITE_REGION:-local}

  faktory:
    volumes:
     - ${DATA_FOLDER_FAKTORY:-./data/dev/faktory}:/var/lib/faktory
    environment:
      - FAKTORY_PASSWORD=${FAKTORY_PASSWORD:-password}
    ports:
      - "7419:7419"
      - "7420:7420"

