version: '3.1'

services:

  createbuckets:
    image: quay.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc admin user add myminio minio_client minio_secret;
      /usr/bin/mc admin policy set myminio readwrite user=minio_client;
      /usr/bin/mc mb myminio/photos;
      /usr/bin/mc mb myminio/miniatures;
      /usr/bin/mc policy set public myminio/photos;
      /usr/bin/mc policy set public myminio/miniatures;
      /usr/bin/mc mb myminio/photos-test;
      /usr/bin/mc mb myminio/miniatures-test;
      /usr/bin/mc policy set public myminio/photos-test;
      /usr/bin/mc policy set public myminio/miniatures-test;
      exit 0;
      "
