version: '3.1'

services:

  db:
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  minio:
    command: server /data
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SITE_REGION: ${MINIO_SITE_REGION}

  #worker:

  api:
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/redwood_prod?connection_limit=1
      S3_URL: http://minio:9000
      SESSION_SECRET: ${SESSION_SECRET}
      SIGNUP_SECRET: ${SIGNUP_SECRET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_PHOTOS: ${S3_BUCKET_PHOTOS}
      S3_BUCKET_MINIATURES: ${S3_BUCKET_MINIATURES}

  web:
    ports:
      - "8100:8100"
    environment:
      PHOTOS_URL: ${PHOTOS_URL}
      MINIATURES_URL: ${MINIATURES_URL}
      GMAPS_API_KEY: ${GMAPS_API_KEY}


volumes:
  database:
