version: '3.1'

services:

  db:
    ports:
      - "5432:5432"
    volumes:
      - ${DATA_FOLDER_DB:-./data/prod/postgres}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${DATA_FOLDER_MINIO:-./data/prod/minio}:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SITE_REGION: ${MINIO_SITE_REGION}

  faktory:
    volumes:
      - ${DATA_FOLDER_FAKTORY:-./data/prod/faktory}:/var/lib/faktory
    environment:
      - FAKTORY_PASSWORD=${FAKTORY_PASSWORD}
    ports:
      - "7419:7419"
      - "7420:7420"
    command: "/faktory -b :7419 -w :7420 -e production"

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    depends_on:
      - db
    environment:
      S3_URL: http://minio:9000
      FAKTORY_URL: http://faktory:7419
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_DB}?connection_limit=1
      SESSION_SECRET: ${SESSION_SECRET}
      SIGNUP_SECRET: ${SIGNUP_SECRET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_PHOTOS: ${S3_BUCKET_PHOTOS}
      S3_BUCKET_MINIATURES: ${S3_BUCKET_MINIATURES}
      FAKTORY_PASSWORD: ${FAKTORY_PASSWORD}

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        PHOTOS_URL: ${PHOTOS_URL}
        MINIATURES_URL: ${MINIATURES_URL}
        GMAPS_API_KEY: ${GMAPS_API_KEY}
    depends_on:
      - api
      - minio
    ports:
      - "8100:8100"

  worker:
    build:
      context: .
      dockerfile: docker/scripts/Dockerfile
    command: [ "worker" ]
    depends_on:
      - minio
      - db
      - faktory
    environment:
      FAKTORY_URL: http://faktory:7419
      S3_URL: http://minio:9000
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_DB}?connection_limit=1
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_PHOTOS: ${S3_BUCKET_PHOTOS}
      S3_BUCKET_MINIATURES: ${S3_BUCKET_MINIATURES}
      FAKTORY_PASSWORD: ${FAKTORY_PASSWORD}

  migrate:
    build:
      context: .
      dockerfile: docker/scripts/Dockerfile
    entrypoint: ["yarn", "rw", "prisma", "migrate", "deploy"]
    command: []
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_DB}?connection_limit=1
