version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}

  minio:
    image: quay.io/minio/minio
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_SITE_REGION: local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  faktory:
    image: contribsys/faktory:latest

  worker:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    command: [ "worker" ]
    depends_on:
      - db
      - faktory

volumes:
  database:
