version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}

  minio:
    image: quay.io/minio/minio
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_SITE_REGION: local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  worker:
    image: contribsys/faktory:latest

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    depends_on:
      - api
      - minio

volumes:
  database:
