[web]
  title = "Barracuda Photos"
  port = 8910
  apiUrl = "/.redwood/functions"
  includeEnvironmentVariables = ['PHOTOS_URL', 'MINIATURES_URL', 'GMAPS_API_KEY']
[api]
  port = 8911
[browser]
  open = false
